basePath: /
definitions:
  handlers.Message:
    properties:
      priority:
        type: string
      text:
        type: string
    type: object
info:
  contact: {}
  description: Telegram Bot which sends messages to channels and groups
  title: Message Sender Bot
  version: "1.0"
paths:
  /send:
    post:
      consumes:
      - application/json
      description: send message
      parameters:
      - description: message_content
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.Message'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: ""
      summary: MessageSender
      tags:
      - Massage
swagger: "2.0"
